- id: '1763853932552'
  alias: Neue Automation
  description: ''
  triggers:
  - device_id: 4edea0fb38c54c43eea6161e8536cf91
    domain: climate
    entity_id: f6cca13c7a1e65eb94dc40f1d232c02a
    type: current_temperature_changed
    trigger: device
    above: 10
  conditions: []
  actions:
  - action: notify.send_message
    metadata: {}
    data:
      message: Test
  - action: todo.add_item
    metadata: {}
    data:
      item: Test1
  mode: single
