blueprint:
  name: Übertemperatur Alarm
  description: Sende eine Push-Benachrichtigung, wenn die Temperatur des Sensors einen bestimmten Schwellenwert überschreitet.
  domain: automation
  input:
    temp_sensor:
      name: Temperatursensor
      selector:
        entity:
          domain: sensor
          device_class: temperature
    threshold:
      name: Obergrenze (°C)
      default: 25
      selector:
        number:
          min: 0
          max: 200
          unit_of_measurement: "°C"

trigger:
  platform: numeric_state
  entity_id: !input temp_sensor
  above: !input threshold

action:
  - service: notify.notify
    data:
      title: "Überhitzungswarnung"
      message: "Der Sensor {{ state_attr(trigger.entity_id, 'friendly_name') }} ist bei {{ trigger.to_state.state }}°C."
  - delay: "02:00:00"