blueprint:
  name: Temperature Push Alert
  description: Sends a push notification to a specific device when temperature is too high.
  domain: automation
  input:
    temp_sensor:
      name: Temperature Sensor
      selector:
        entity:
          domain: sensor
          device_class: temperature
    threshold:
      name: Threshold
      default: 25
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "°C"
    notify_device:
      name: Device to notify
      description: Select the device running the Home Assistant app.
      selector:
        device:
          integration: mobile_app

trigger:
  platform: numeric_state
  entity_id: !input temp_sensor
  above: !input threshold

action:
  - domain: mobile_app
    type: notify
    device_id: !input notify_device
    title: "High Temp Alert!"
    message: "The sensor {{ state_attr(trigger.entity_id, 'friendly_name') }} is at {{ trigger.to_state.state }}°C."